package ua.java.conferences.model.dao.mysql.constants;

import lombok.*;

/**
 * Class that contains all My SQL database fields
 *
 * @author Vitalii Kalinchyk
 * @version 1.0
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class SQLFields {
    /** Common id field for user, report an event tables */
    public static final String ID = "id";

    /** Fields for user table */
    public static final String EMAIL = "email";
    public static final String PASSWORD = "password";
    public static final String NAME = "name";
    public static final String SURNAME = "surname";
    public static final String ROLE_ID = "role_id";

    /** Fields for event table */
    public static final String TITLE = "title";
    public static final String DATE = "date";
    public static final String LOCATION = "location";
    public static final String DESCRIPTION = "description";
    public static final String VISITORS = "visitors";

    /** Fields for report table */
    public static final String TOPIC = "topic";

    /** ID fields in user_has_event and report tables */
    public static final String USER_ID = "user_id";
    public static final String EVENT_ID = "event_id";

    /** Fields generated by queries */
    public static final String NUMBER_OF_RECORDS = "numberOfRecords";
    public static final String REGISTRATIONS = "registrations";
    public static final String REPORTS = "reports";
}