package ua.java.conferences.model.dao.mysql;

import lombok.extern.slf4j.Slf4j;
import ua.java.conferences.model.dao.EventDAO;
import ua.java.conferences.model.entities.Event;
import ua.java.conferences.model.entities.role.Role;
import ua.java.conferences.exceptions.DAOException;

import javax.sql.DataSource;
import java.sql.*;
import java.sql.Date;
import java.util.*;

import static ua.java.conferences.model.dao.mysql.constants.EventSQLQueries.*;
import static ua.java.conferences.model.dao.mysql.constants.SQLFields.*;
import static ua.java.conferences.model.entities.role.Role.SPEAKER;

/**
 * Event DAO class for My SQL database. Matches table 'event' in database.
 *
 * @author Vitalii Kalinchyk
 * @version 1.0
 */
@Slf4j
public class MysqlEventDAO implements EventDAO {
    private final DataSource dataSource;

    /** The only constructor to get DAO instance
     * @param dataSource to get connection to database
     */
    public MysqlEventDAO(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * Inserts new event to database
     * @param event - id will be generated by database. Date, location and description should be not null
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void add(Event event) throws DAOException {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(ADD_EVENT)) {
            int k = 0;
            setStatementFields(event, preparedStatement, k);
            preparedStatement.execute();
        } catch (SQLException e) {
            log.error(String.format("Couldn't add new event '%s' because of %s", event.getTitle(), e.getMessage()));
            throw new DAOException(e);
        }
    }

    /**
     * Obtains instance of Event from database by id
     * @param id - value of id field in database
     * @return Optional.ofNullable - event is null if there is no event
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public Optional<Event> getById(long id) throws DAOException {
        Event event = null;
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(GET_EVENT_BY_ID)) {
            setId(id, preparedStatement);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    event = createEvent(resultSet);
                }
            }
        } catch (SQLException e) {
            log.error(String.format("Couldn't find event with id=%d because of %s", id, e.getMessage()));
            throw new DAOException(e);
        }
        return Optional.ofNullable(event);
    }

    /**
     * Obtains instance of Event from database by title
     * @param title - value of title field in database
     * @return Optional.ofNullable - event is null if there is no event
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public Optional<Event> getByTitle(String title) throws DAOException {
        Event event = null;
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(GET_EVENT_BY_TITLE)) {
            int k = 0;
            preparedStatement.setString(++k, title);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    event = createEvent(resultSet);
                }
            }
        } catch (SQLException e) {
            log.error(String.format("Couldn't find event %s because of %s", title, e.getMessage()));
            throw new DAOException(e);
        }
        return Optional.ofNullable(event);
    }

    /**
     * Obtains list of all events from database
     * @return events list
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public List<Event> getAll() throws DAOException {
        List<Event> events = new ArrayList<>();
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(GET_EVENTS)) {
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    events.add(createEvent(resultSet));
                }
            }
        } catch (SQLException e) {
            log.error(String.format("Couldn't get list of all events because of %s", e.getMessage()));
            throw new DAOException(e);
        }
        return events;
    }

    /**
     * Obtains sorted and limited list of events from database
     * @param query should contain filters (where), order (order field and type), limits for pagination
     * @return events list that matches demands. Will be empty if there are no events
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public List<Event> getSorted(String query) throws DAOException {
        List<Event> events = new ArrayList<>();
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(String.format(GET_SORTED, query))) {
            preparedStatement.execute();
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    events.add(createEvent(resultSet));
                }
            }
        } catch (SQLException e) {
            log.error(String.format("Couldn't get sorted list of events because of %s", e.getMessage()));
            throw new DAOException(e);
        }
        return events;
    }

    /**
     * Obtains sorted and limited list of events from database
     * @param query should contain filters (where), order (order field and type), limits for pagination
     * @param role should be either VISITOR or SPEAKER
     * @return events list that matches demands
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public List<Event> getSortedByUser(String query, Role role) throws DAOException {
        List<Event> events = new ArrayList<>();
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(getQueryForList(query, role))) {
            preparedStatement.execute();
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    events.add(createUserEvent(resultSet));
                }
            }
        } catch (SQLException e) {
            log.error(String.format("Couldn't get sorted list of events because of %s", e.getMessage()));
            throw new DAOException(e);
        }
        return events;
    }

    /**
     * Updates event
     * @param event should contain id, title, date and description to be updated
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void update(Event event) throws DAOException {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(EDIT_EVENT)) {
            int k = 0;
            k = setStatementFields(event, preparedStatement, k);
            preparedStatement.setLong(++k, event.getId());
            preparedStatement.execute();
        } catch (SQLException e) {
            log.error(String.format("Couldn't update event %s because of %s", event.getTitle(), e.getMessage()));
            throw new DAOException(e);
        }
    }

    /**
     * Updates event's visitors field
     * @param eventId - value of id field in database
     * @param visitorsCount - value of visitor field in database
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void setVisitorsCount(long eventId, int visitorsCount) throws DAOException {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(SET_VISITORS)) {
            int k = 0;
            preparedStatement.setInt(++k, visitorsCount);
            preparedStatement.setLong(++k, eventId);
            preparedStatement.execute();
        } catch (SQLException e) {
            log.error(String.format("Couldn't set visitors for event with id=%d because of %s", eventId, e.getMessage()));
            throw new DAOException(e);
        }
    }

    /**
     * Deletes event record in database
     * @param id - value of id field in database
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void delete(long id) throws DAOException {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(DELETE_EVENT)) {
            setId(id, preparedStatement);
            preparedStatement.execute();
        } catch (SQLException e) {
            log.error(String.format("Couldn't delete event with id=%d because of %s", id, e.getMessage()));
            throw new DAOException(e);
        }
    }

    /**
     * Obtains number of all records matching filter
     * @param filter should contain 'where' to specify query
     * @param role can be VISITOR, SPEAKER or any other
     * @return number of records
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public int getNumberOfRecords (String filter, Role role) throws DAOException {
        int numberOfRecords = 0;
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(getRecordsQuery(filter, role))) {
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    numberOfRecords = resultSet.getInt(NUMBER_OF_RECORDS);
                }
            }
        } catch (SQLException e) {
            log.error(String.format("Couldn't get number of events because of %s", e.getMessage()));
            throw new DAOException(e);
        }
        return numberOfRecords;
    }

    private String getRecordsQuery(String filter, Role role) {
        switch (role) {
            case VISITOR: return String.format(GET_NUMBER_OF_RECORDS_BY_VISITOR, filter);
            case SPEAKER: return String.format(GET_NUMBER_OF_RECORDS_BY_SPEAKER, filter);
            default: return String.format(GET_NUMBER_OF_RECORDS, filter);
        }
    }

    private String getQueryForList(String query, Role role) {
        return role == SPEAKER ? String.format(GET_SPEAKERS_EVENTS, query)
                               : String.format(GET_VISITORS_EVENTS, query);
    }

    private void setId(long id, PreparedStatement preparedStatement) throws SQLException {
        int k = 0;
        preparedStatement.setLong(++k, id);
    }

    private int setStatementFields(Event event, PreparedStatement preparedStatement, int k) throws SQLException {
        preparedStatement.setString(++k, event.getTitle());
        preparedStatement.setDate(++k, Date.valueOf(event.getDate()));
        preparedStatement.setString(++k, event.getLocation());
        preparedStatement.setString(++k, event.getDescription());
        return k;
    }

    private Event createEvent(ResultSet resultSet) throws SQLException {
        return Event.builder()
                .id(resultSet.getLong(ID))
                .title(resultSet.getString(TITLE))
                .date(resultSet.getDate(DATE).toLocalDate())
                .location(resultSet.getString(LOCATION))
                .description(resultSet.getString(DESCRIPTION))
                .registrations(resultSet.getInt(REGISTRATIONS))
                .visitors(resultSet.getInt(VISITORS))
                .reports(resultSet.getInt(REPORTS))
                .build();
    }

    private Event createUserEvent(ResultSet resultSet) throws SQLException {
        return Event.builder()
                .id(resultSet.getLong(ID))
                .title(resultSet.getString(TITLE))
                .date(resultSet.getDate(DATE).toLocalDate())
                .location(resultSet.getString(LOCATION))
                .description(resultSet.getString(DESCRIPTION))
                .build();
    }
}